on:
  pull_request:
    branches: 
      - main
    types: [closed]


jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/pysimpler/
    permissions:
      id-token: write  
    steps:

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: mpektas
        password: ${{ secrets.PYPI_TOKEN }}
        # If you want to upload to TestPyPI, uncomment the following line
        repository_url: https://test.pypi.org/legacy/